//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProyectoPAV2doAvance.rc
//
#define BTN_Alta_Comercio_Guardar       3
#define DLG_Registro_Admin              9
#define DLG_Comercio                    101
#define DLG_Login                       105
#define IDR_MENU1                       109
#define DLG_Principal_Admin             110
#define DLG_Actualizar_User             112
#define DLG_Alta_User                   114
#define DLG_Listado_User                116
#define DLG_Alta_Clientes               118
#define DLG_Listado_Clientes            120
#define DLG_Actualizar_Cliente          122
#define DLG_Alta_Promociones            124
#define DLG_Listado_Promos              126
#define DLG_Actualizar_Promo            128
#define DLG_Alta_Consumos               130
#define DLG_Listado_Consumos            132
#define DLG_Principal_Cajero            134
#define DLG_Alta_Comercio               136
#define DLG_actualizar_pass             139
#define IDR_MENU2                       141
#define BTN_Comercio_Aceptar            1001
#define BTN_Comercios_Salir             1002
#define BTN_Comercios_Registrar         1003
#define LB_Comercios                    1005
#define BTN_Login_Registrar             1006
#define BTN_Login                       1007
#define BTN_Login_Salir                 1008
#define EC_Listado_Promo_Status         1009
#define EC_Login_User                   1011
#define EC_Login_Pass                   1012
#define BTN_Registro_Admin              1014
#define BTN_Registro_Admin_cancel       1015
#define EC_Registro_Admin_User          1016
#define EC_Registro_Admin_Pass          1017
#define EC_Principal_Admin_Cantidad_Clientes 1019
#define EC_Principal_Admin_Cantidad_Promos 1022
#define EC_Principal_Admin_Cantidad_Promos_Activas 1023
#define EC_Principal_Admin_Cantidad_Promos_Inactivas 1024
#define EC_Principal_Admin_Cantidad_Consumos 1026
#define EC_Principal_Admin_Cantidad_ConsumosTotal 1027
#define EC_Principal_Admin_User         1028
#define EC_Alta_User_Comercio           1029
#define EC_Actualizar_User_User         1031
#define EC_Actualizar_User_FullName     1032
#define EC_Actualizar_User_Alias        1033
#define BTN_Actualizar_User_Modificar_Pass 1035
#define BTN_Actualizar_User_Modificar_foto 1036
#define Pic_Actualizar_User_foto        1037
#define BTN_Actualizar_User_Volver      1038
#define BTN_Actualizar_User_Guardar     1039
#define EC_Alta_User_Username           1040
#define EC_Alta_User_Pass               1041
#define RB_Alta_User_Admin              1042
#define RB_Alta_User_Cajero             1043
#define BTN_Alta_User_Aceptar           1044
#define BTN_Alta_User_cancelar          1045
#define LB_Listado_User                 1046
#define EC_Alta_User_Username2          1046
#define EC_Listado_User_Comercio        1047
#define EC_Listado_User_Username        1048
#define EC_Principal_Admin_User2        1049
#define EC_Listado_User_Fullname        1049
#define EC_Listado_User_Alias           1050
#define BTN_Listado_User_Regresar       1053
#define BTN_Listado_User_Actualizar     1054
#define BTN_Listado_User_Eliminar       1055
#define Pic_Listado_User_Foto           1056
#define EC_Alta_Cliente_name            1057
#define EC_Alta_Cliente_Comercio        1058
#define EC_Alta_Cliente_Email           1059
#define EC_Alta_Cliente_Alias           1060
#define EC_Alta_Cliente_Telefono        1061
#define EC_Alta_Cliente_Fecha           1062
#define BTN_Alta_Cliente_Guardar        1063
#define BTN_Alta_Cliente_Regresar       1064
#define IDC_LIST1                       1065
#define LB__Listado_Clientes            1065
#define LB_Listado_promos               1065
#define LB_Listado_Consumos             1065
#define EC_Alta_Cliente_Email2          1065
#define EC_Listado_Clientes_Nombre      1066
#define EC_Alta_Cliente_Email3          1066
#define EC_Listado_Clientes_Alias       1067
#define EC_Listado_Clientes_Telefono    1068
#define EC_Listado_Clientes_Email       1069
#define EC_Listado_Clientes_Comercio    1070
#define EC_Listado_Clientes_Email2      1070
#define EC_Listado_Clientes_Fecha       1071
#define BTN_Listado_Clientes_Regresar   1072
#define BTN_Listado_Clientes_Modificar  1073
#define BTN_Listado_Clientes_Eliminar   1074
#define EC_Actualizar_Clientes_Nombre   1075
#define EC_Actualizar_Clientes_Alias    1076
#define EC_Actualizar_Clientes_Telefono 1077
#define EC_Actualizar_Clientes_Email    1078
#define EC_Actualizar_Clientes_Comercio 1079
#define EC_Actualizar_Clientes_Email2   1079
#define EC_Actualizar_Clientes_Fecha    1080
#define BTN_Actualizar_Clientes_Guardar 1081
#define BTN_Actualizar_Clientes_Cancelar 1082
#define EC_Alta_Promo_Name              1083
#define EC_Alta_Promo_Monto             1084
#define EC_Alta_Promo_Descuento         1085
#define EC_Alta_Promo_Fecha             1086
#define RB_Alta_Promo_Status_Activo     1087
#define RB_Alta_Promo_Status_Inactivo   1088
#define BTN_Alta_Promos_Guardar         1089
#define BTN_Alta_Promos_Regresar        1090
#define BTN_Listado_Promos_Guardar      1091
#define BTN_Listado_Promos_Eliminar     1092
#define EC_Listado_Promo_Fecha          1093
#define EC_Listado_Promo_Descuento      1094
#define EC_Listado_Promo_Monto          1095
#define EC_Listado_Promo_Name           1096
#define BTN_Listado_Promos_Regresar     1097
#define EC_Actualizar_Promo_Fecha       1098
#define RB_Actualizar_Promo_Status_Activo 1099
#define RB_Actualizar_Promo_Status_Inactivo 1100
#define EC_Actualizar_Promo_Descuento   1101
#define EC_Actualizar_Promo_Monto       1102
#define EC_Actualizar_Promo_Name        1103
#define BTN_Actualizar_Promos_Guardar   1104
#define BTN_Actualizar_Promos_Regresar  1105
#define EC_Alta_Consumos_Monto          1106
#define EC_Alta_Consumos_Fecha          1107
#define EC_Alta_Consumos_Subtotal       1108
#define EC_Alta_Consumos_Descuento      1109
#define EC_Alta_Consumos_Total          1110
#define CB__Alta_Consumos_Cliente       1111
#define BTN_Alta_Consumos_Guardar       1112
#define BTN_Alta_Consumos_Regresar      1113
#define CB_Listado_Consumos_Clientes    1114
#define EC_Listado_Consumos_Monto       1115
#define EC_Listado_Consumos_Fecha       1116
#define EC_Listado_Consumos_Subtotal    1117
#define EC_Listado_Consumos_Descuento   1118
#define EC_Listado_Consumos_Total       1119
#define BTN_Listado_Consumos_Regresar   1120
#define EC_Principal_Admin_Users        1121
#define EC_Principal_Cajero_Cantidad_Clientes 1122
#define EC_Principal_Cajero_Cantidad_Promos 1123
#define EC_Principal_Cajero_Cantidad_Promos_Activas 1124
#define EC_Principal_Cajero_Cantidad_Promos_Inactivas 1125
#define EC_Principal_Cajero_Cantidad_Consumos 1126
#define EC_Principal_Cajero_Cantidad_ConsumosTotal 1127
#define EC_Principal_Cajero_User        1128
#define BTN_Principal_Cajero_unlogin    1129
#define BTN_Principal_Admin_unlogin     1130
#define EC_Alta_Comercio_Name           1131
#define BTN_Alta_Comercio_Salir         1132
#define BTN_Listado_Promo_Actualizar    1133
#define BTN_Listado_User_mostrar        1137
#define EC_actualizar_Pass              1138
#define BTN_actualizar_Pass_Aceptar     1139
#define TN_actualizar_Pass_Cancelar     1140
#define Pic_Principal_User_Foto         1141
#define BTN_Listado_Cliente_Mostrar     1142
#define BTN_Listado_Consumo_clientes    1145
#define BTN_Listado_Consumo_Detalles    1146
#define EC_Listado_Consumo_Cliente      1147
#define EC_Principal_Cajero_User2       1148
#define Menu_CONSUMOS_LISTADO           40025
#define Menu_CONSUMOS_ALTA              40026
#define Menu_PROMOCIONES_ALTA           40027
#define Menu_PROMOCIONES_LISTADO        40028
#define Menu_CLIENTES_ALTA              40029
#define Menu_CLIENTES_LISTADO           40031
#define Menu_USUARIOS_ALTA              40032
#define Menu_USUARIOS_LISTADO           40034
#define Menu_GUARDARCOMO_TXT            40035
#define CMenu_GUARDARCOMO_CSV           40046
#define CMenu_USUARIOS_LISTADO          40047
#define CMenu_CLIENTES_ALTA             40048
#define CMenu_CLIENTES_LISTADO          40049
#define CMenu_PROMOCIONES_ALTA          40050
#define CMenu_PROMOCIONES_LISTADO       40051
#define CMenu_CONSUMOS_ALTA             40052
#define CMenu_CONSUMOS_LISTADO          40053
#define CCMenu_GUARDARCOMO_CSV          40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
